[build]
  command = "npm run build && npm run tina:build"
  publish = "build" # Or wherever your static files are generated

[[functions]]
  directory = "netlify/functions" 
  
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
