[build]
  command = "npx @tinacms/cli build  --verbose && ls -R tina/__generated__ && npm run tina:build"
  publish = "build" # Or wherever your static files are generated

[functions]
  directory = "functions"
  
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
