[build]
  command = "npx @tinacms/cli build  --verbose && npm run build && ls -la && npm run tina:build && npm run postbuild && ls -la build"
  publish = "build" # Or wherever your static files are generated

[functions]
  directory = "functions"
  
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
