[build]
  command = "npm run build  && npm run tina:build && npm run postbuild && esbuild index.js --bundle --minify --platform=node --target=node14 --outfile=dist/index.js "
  publish = "build" # Or wherever your static files are generated

[functions]
  directory = "functions"
  
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
