[build]
  command = "npm run build  && npm run tina:build  && npm run postbuild "
  publish = "build" # Or wherever your static files are generated
  functions = "dist/functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
 from = "/admin/*"
  to = "/admin/index.html"
  status = 200